spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

cookie:
  secure: false

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  api-docs:
    enabled: true