spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false

cookie:
  secure: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
